// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi1Vw05G-xIKBob4GP-S8sXT4LUpO3JWs',
    appId: '1:895744714303:web:58951ee164b52827f4fa8a',
    messagingSenderId: '895744714303',
    projectId: 'study-buddy-app-e4ac9',
    authDomain: 'study-buddy-app-e4ac9.firebaseapp.com',
    storageBucket: 'study-buddy-app-e4ac9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtN2QMZETkBrjnaWS7kJn27Oo2vY40caU',
    appId: '1:895744714303:android:2a8b65983aa9d3c8f4fa8a',
    messagingSenderId: '895744714303',
    projectId: 'study-buddy-app-e4ac9',
    storageBucket: 'study-buddy-app-e4ac9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr8lz9tDjENUPOo0A2HV5JRgI4s2QfAnA',
    appId: '1:895744714303:ios:d8ec66c0a983654ef4fa8a',
    messagingSenderId: '895744714303',
    projectId: 'study-buddy-app-e4ac9',
    storageBucket: 'study-buddy-app-e4ac9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr8lz9tDjENUPOo0A2HV5JRgI4s2QfAnA',
    appId: '1:895744714303:ios:d8ec66c0a983654ef4fa8a',
    messagingSenderId: '895744714303',
    projectId: 'study-buddy-app-e4ac9',
    storageBucket: 'study-buddy-app-e4ac9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi1Vw05G-xIKBob4GP-S8sXT4LUpO3JWs',
    appId: '1:895744714303:web:7c1f5a2fd23b5629f4fa8a',
    messagingSenderId: '895744714303',
    projectId: 'study-buddy-app-e4ac9',
    authDomain: 'study-buddy-app-e4ac9.firebaseapp.com',
    storageBucket: 'study-buddy-app-e4ac9.firebasestorage.app',
  );
}
